name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7.5
          - 3.0.3
          - 3.1.1
        mongodb:
          - 4.2
          - 4.4
          - 5.0

    name: Ruby ${{ matrix.ruby }} sample

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb }}

      - name: Run rubocop
        run: |
          bundle exec rubocop
      - name: Run tests
        run: |
          bundle exec rspec